# Generated by Django 5.2.7 on 2025-11-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto_url',
            field=models.CharField(blank=True, help_text='URL a una imagen de perfil (ej. imgur)', max_length=500, null=True),
        ),
    ]
