# Generated by Django 5.2.7 on 2025-11-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_registroauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='almacenamiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipos',
            name='procesador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipos',
            name='ram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
