# Generated by Django 5.2.7 on 2025-11-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_equipos_almacenamiento_equipos_procesador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='factura',
            field=models.FileField(blank=True, null=True, upload_to='facturas_equipos/'),
        ),
    ]
