# Generated by Django 5.2.7 on 2025-11-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_equipos_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='foto',
        ),
    ]
