# Generated by Django 5.2.8 on 2025-12-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_actividad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estados',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='proveedores',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tiposdeequipo',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='actividad',
            name='due_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
