# Generated by Django 5.2.8 on 2025-12-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_estados_options_alter_proveedores_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
