# Generated by Django 5.2.8 on 2025-12-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_sucursal_equipos_id_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
